### ISSUE TITLE
how to run this given the dataset about sequence of items viewed in sessions and also baskets ?

### ISSUE THREAD

**Issue by anuragreddygv323** [IlyaTrofimov/bb2vec#1]
could you help me understand the input format and outputformat 

how to run this script ?

**Comment by IlyaTrofimov** [comment]
Hi, I added the simple example:
https://github.com/IlyaTrofimov/bb2vec/blob/master/example.sh
Also you can check the possible options by 
./acc-rec --help

Baskets format: basket_id \t item_id
Views format: item1_id \t item2_id \t PMI

**Comment by anuragreddygv323** [comment]
./acc-rec -b test/baskets.train.10p.txt --val test/baskets.val.txt -v test/views.txt -t 8 --iter 5 --rank
baskets.train.10p.txt - has 2 products. could you help me how did u create this ?

baskets.val.txt - is this the validation dataset?

views.txt has product1 product2 and PMI - how to calculate PMI and send it as an input ?

how are u using item features ?

**Comment by anuragreddygv323** [comment]
I am getting "-bash: ./acc-rec: No such file or directory"

./acc-rec -b test/baskets.train.10p.txt --val test/baskets.val.txt -v test/views.txt -t 8 --iter 5 --rank

could you help me with the exact steps to replicate the example shared. it will be very helpful.

Thanks,
Anurag

**Comment by anuragreddygv323** [comment]
After compiling using 
g++ acc-rec.cpp

acc-rec.cpp:17:10: fatal error: 'boost/program_options.hpp' file not found
#include <boost/program_options.hpp>
         ^~~~~~~~~~~~~~~~~~~~~~~~~~~
1 error generated.

can u look into this ?

**Comment by IlyaTrofimov** [comment]
Try to run  `sudo apt-get install libboost-program-options1.55-dev` before compilation.

**Comment by anuragreddygv323** [comment]
I am using Mac. Will it still work ?

**Comment by IlyaTrofimov** [comment]
Here is an instruction for boost installation for Mac from another ml project, might be helpful for you
https://github.com/VowpalWabbit/vowpal_wabbit#osx-dependencies-if-using-brew

**Comment by anne1994** [comment]
@anuragreddygv323  did u get to run the script? did you get to install boost ? if yes, can i know how ?
